version: '3.8'

services:
  couchdb:
    image: couchdb:latest 
    container_name: WDK_Referat_Davtyan
    restart: unless-stopped 
    ports:
      - "5984:5984" 
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - couchdb_data:/opt/couchdb/data 

volumes:
  couchdb_data:
